/**
 * schema.org vocabulary validation for every JSON-LD block we emit.
 *
 * Where `jsonld-validate.ts` checks shape and `jsonld-rich-results.ts` checks
 * Google eligibility, this module checks the structured data against the
 * *official schema.org vocabulary snapshot* (src/lib/schema-org-vocabulary.json,
 * regenerated by scripts/gen-schema-vocabulary.mjs):
 *
 *   - every `@type` is a real schema.org type (error)
 *   - every property exists in the schema.org vocabulary (error)
 *   - every property is valid on its node's type via the class hierarchy,
 *     i.e. domainIncludes matches the type or one of its supertypes (warning)
 *   - `@context` resolves to schema.org (error)
 *
 * CI runs this in strict mode, where warnings fail the build too.
 */
import vocabulary from "./schema-org-vocabulary.json";

export type SchemaOrgSeverity = "error" | "warning";

export type SchemaOrgIssue = {
  source: string;
  path: string;
  type: string;
  severity: SchemaOrgSeverity;
  code: string;
  message: string;
};

export type SchemaOrgReport = {
  source: string;
  nodes: number;
  issues: SchemaOrgIssue[];
  errors: SchemaOrgIssue[];
  warnings: SchemaOrgIssue[];
};

export const SCHEMA_ORG_VERSION: string = vocabulary.version;

const TYPES = vocabulary.types as Record<string, string[]>;
const PROPERTIES = vocabulary.properties as Record<string, string[]>;
const ENUM_MEMBERS = new Set(vocabulary.enumerations as string[]);

/** JSON-LD keywords that are never schema.org properties. */
const JSONLD_KEYWORDS = new Set([
  "@context",
  "@type",
  "@id",
  "@graph",
  "@list",
  "@set",
  "@value",
  "@language",
  "@reverse",
  "@base",
  "@vocab",
  "@container",
  "@index",
  "@nest",
  "@none",
  "@json",
]);

/**
 * Google-documented extensions that are not part of the schema.org core
 * vocabulary but are required by their rich-result specs.
 */
const GOOGLE_EXTENSIONS = new Set(["query-input"]);

/**
 * Types published on pending.schema.org — real, documented vocabulary terms
 * that are not yet in the core snapshot. Mapped to their core supertype so
 * property-domain checks still resolve through the class hierarchy.
 */
const PENDING_TYPES: Record<string, string[]> = {
  CryptoCurrency: ["FinancialProduct"],
};

const isRecord = (v: unknown): v is Record<string, unknown> =>
  typeof v === "object" && v !== null && !Array.isArray(v);

const asArray = <T,>(v: T | T[] | undefined): T[] =>
  v === undefined || v === null ? [] : Array.isArray(v) ? v : [v];

const localName = (value: string): string =>
  value.replace(/^https?:\/\/schema\.org\//, "").replace(/^schema:/, "");

const supertypesOf = (name: string): string[] | undefined =>
  TYPES[name] ?? PENDING_TYPES[name];

export const isSchemaOrgType = (name: string): boolean =>
  supertypesOf(localName(name)) !== undefined;

export const isSchemaOrgProperty = (name: string): boolean =>
  Object.prototype.hasOwnProperty.call(PROPERTIES, name);

export const isSchemaOrgEnumerationMember = (name: string): boolean =>
  ENUM_MEMBERS.has(localName(name));

/** Full ancestor chain (inclusive) for a schema.org type. */
export function typeAncestors(name: string): string[] {
  const seen = new Set<string>();
  const queue = [localName(name)];
  while (queue.length) {
    const current = queue.shift()!;
    const parents = supertypesOf(current);
    if (seen.has(current) || !parents) continue;
    seen.add(current);
    queue.push(...parents);
  }
  return [...seen];
}

/** True when `property` is declared on `type` or any of its supertypes. */
export function propertyAppliesTo(property: string, types: string[]): boolean {
  const domains = PROPERTIES[property];
  if (!domains || domains.length === 0) return true; // property with no stated domain
  const ancestors = new Set(types.flatMap((t) => typeAncestors(t)));
  return domains.some((domain) => ancestors.has(localName(domain)));
}

function contextIsSchemaOrg(context: unknown): boolean {
  const entries = asArray(context as unknown);
  return entries.some((entry) => {
    if (typeof entry === "string") return /^https?:\/\/schema\.org\/?$/.test(entry);
    if (isRecord(entry)) {
      return Object.values(entry).some(
        (v) => typeof v === "string" && /^https?:\/\/schema\.org\/?$/.test(v),
      );
    }
    return false;
  });
}

function walk(
  node: unknown,
  path: string,
  source: string,
  issues: SchemaOrgIssue[],
  counter: { nodes: number },
): void {
  if (Array.isArray(node)) {
    node.forEach((child, index) => walk(child, `${path}[${index}]`, source, issues, counter));
    return;
  }
  if (!isRecord(node)) return;

  counter.nodes += 1;

  const rawTypes = asArray(node["@type"] as string | string[] | undefined).filter(
    (t): t is string => typeof t === "string",
  );
  const types = rawTypes.map(localName);
  const label = types.join(",") || "(untyped)";

  for (const type of types) {
    if (!isSchemaOrgType(type)) {
      issues.push({
        source,
        path,
        type: label,
        severity: "error",
        code: "unknown-type",
        message: isSchemaOrgEnumerationMember(type)
          ? `"${type}" is a schema.org enumeration member, not a type — use it as a property value.`
          : `"${type}" is not a type in the schema.org vocabulary (${SCHEMA_ORG_VERSION}).`,
      });
    }
  }

  const knownTypes = types.filter(isSchemaOrgType);

  for (const key of Object.keys(node)) {
    if (JSONLD_KEYWORDS.has(key) || GOOGLE_EXTENSIONS.has(key)) continue;

    if (!isSchemaOrgProperty(key)) {
      issues.push({
        source,
        path: `${path}.${key}`,
        type: label,
        severity: "error",
        code: "unknown-property",
        message: `"${key}" is not a property in the schema.org vocabulary.`,
      });
    } else if (knownTypes.length > 0 && !propertyAppliesTo(key, knownTypes)) {
      issues.push({
        source,
        path: `${path}.${key}`,
        type: label,
        severity: "warning",
        code: "property-domain-mismatch",
        message: `"${key}" is not defined for ${label} (schema.org domain: ${PROPERTIES[key].join(", ")}).`,
      });
    }

    walk(node[key], `${path}.${key}`, source, issues, counter);
  }

  if (knownTypes.length === 0 && rawTypes.length === 0 && path !== "root") {
    // Untyped nested objects are allowed (value objects) — nothing to check.
  }
}

/** Validate one or more parsed JSON-LD documents against schema.org. */
export function checkSchemaOrg(docs: unknown[], source: string): SchemaOrgReport {
  const issues: SchemaOrgIssue[] = [];
  const counter = { nodes: 0 };

  docs.forEach((doc, index) => {
    const path = docs.length > 1 ? `root[${index}]` : "root";
    if (isRecord(doc) && !contextIsSchemaOrg(doc["@context"])) {
      issues.push({
        source,
        path: `${path}.@context`,
        type: "(document)",
        severity: "error",
        code: "invalid-context",
        message: "@context must resolve to https://schema.org.",
      });
    }
    const graph = isRecord(doc) && Array.isArray(doc["@graph"]) ? doc["@graph"] : null;
    if (graph) {
      graph.forEach((child, i) => walk(child, `${path}.@graph[${i}]`, source, issues, counter));
    } else {
      walk(doc, path, source, issues, counter);
    }
  });

  return {
    source,
    nodes: counter.nodes,
    issues,
    errors: issues.filter((i) => i.severity === "error"),
    warnings: issues.filter((i) => i.severity === "warning"),
  };
}

export function formatSchemaOrgIssues(issues: SchemaOrgIssue[]): string {
  return issues
    .map(
      (i) =>
        `  ${i.severity === "error" ? "✗" : "!"} [${i.code}] ${i.source} ${i.path} (${i.type}): ${i.message}`,
    )
    .join("\n");
}
