/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PaperRouteImport } from './routes/paper'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetSymbolRouteImport } from './routes/asset.$symbol'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperRoute = PaperRouteImport.update({
  id: '/paper',
  path: '/paper',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetSymbolRoute = AssetSymbolRouteImport.update({
  id: '/asset/$symbol',
  path: '/asset/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/backtest': typeof BacktestRoute
  '/community': typeof CommunityRoute
  '/copilot': typeof CopilotRoute
  '/doctor': typeof DoctorRoute
  '/journal': typeof JournalRoute
  '/learn': typeof LearnRoute
  '/paper': typeof PaperRoute
  '/pricing': typeof PricingRoute
  '/risk': typeof RiskRoute
  '/scanner': typeof ScannerRoute
  '/security': typeof SecurityRoute
  '/strategy': typeof StrategyRoute
  '/asset/$symbol': typeof AssetSymbolRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/backtest': typeof BacktestRoute
  '/community': typeof CommunityRoute
  '/copilot': typeof CopilotRoute
  '/doctor': typeof DoctorRoute
  '/journal': typeof JournalRoute
  '/learn': typeof LearnRoute
  '/paper': typeof PaperRoute
  '/pricing': typeof PricingRoute
  '/risk': typeof RiskRoute
  '/scanner': typeof ScannerRoute
  '/security': typeof SecurityRoute
  '/strategy': typeof StrategyRoute
  '/asset/$symbol': typeof AssetSymbolRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/backtest': typeof BacktestRoute
  '/community': typeof CommunityRoute
  '/copilot': typeof CopilotRoute
  '/doctor': typeof DoctorRoute
  '/journal': typeof JournalRoute
  '/learn': typeof LearnRoute
  '/paper': typeof PaperRoute
  '/pricing': typeof PricingRoute
  '/risk': typeof RiskRoute
  '/scanner': typeof ScannerRoute
  '/security': typeof SecurityRoute
  '/strategy': typeof StrategyRoute
  '/asset/$symbol': typeof AssetSymbolRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/auth'
    | '/backtest'
    | '/community'
    | '/copilot'
    | '/doctor'
    | '/journal'
    | '/learn'
    | '/paper'
    | '/pricing'
    | '/risk'
    | '/scanner'
    | '/security'
    | '/strategy'
    | '/asset/$symbol'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/auth'
    | '/backtest'
    | '/community'
    | '/copilot'
    | '/doctor'
    | '/journal'
    | '/learn'
    | '/paper'
    | '/pricing'
    | '/risk'
    | '/scanner'
    | '/security'
    | '/strategy'
    | '/asset/$symbol'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/auth'
    | '/backtest'
    | '/community'
    | '/copilot'
    | '/doctor'
    | '/journal'
    | '/learn'
    | '/paper'
    | '/pricing'
    | '/risk'
    | '/scanner'
    | '/security'
    | '/strategy'
    | '/asset/$symbol'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AuthRoute: typeof AuthRoute
  BacktestRoute: typeof BacktestRoute
  CommunityRoute: typeof CommunityRoute
  CopilotRoute: typeof CopilotRoute
  DoctorRoute: typeof DoctorRoute
  JournalRoute: typeof JournalRoute
  LearnRoute: typeof LearnRoute
  PaperRoute: typeof PaperRoute
  PricingRoute: typeof PricingRoute
  RiskRoute: typeof RiskRoute
  ScannerRoute: typeof ScannerRoute
  SecurityRoute: typeof SecurityRoute
  StrategyRoute: typeof StrategyRoute
  AssetSymbolRoute: typeof AssetSymbolRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper': {
      id: '/paper'
      path: '/paper'
      fullPath: '/paper'
      preLoaderRoute: typeof PaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset/$symbol': {
      id: '/asset/$symbol'
      path: '/asset/$symbol'
      fullPath: '/asset/$symbol'
      preLoaderRoute: typeof AssetSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AuthRoute: AuthRoute,
  BacktestRoute: BacktestRoute,
  CommunityRoute: CommunityRoute,
  CopilotRoute: CopilotRoute,
  DoctorRoute: DoctorRoute,
  JournalRoute: JournalRoute,
  LearnRoute: LearnRoute,
  PaperRoute: PaperRoute,
  PricingRoute: PricingRoute,
  RiskRoute: RiskRoute,
  ScannerRoute: ScannerRoute,
  SecurityRoute: SecurityRoute,
  StrategyRoute: StrategyRoute,
  AssetSymbolRoute: AssetSymbolRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
