/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdsReportRouteImport } from './routes/ads-report'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as GoLiveTestRouteImport } from './routes/go-live-test'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LpReportRouteImport } from './routes/lp-report'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as McpConsoleRouteImport } from './routes/mcp-console'
import { Route as PaperRouteImport } from './routes/paper'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReferRouteImport } from './routes/refer'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as RiskRouteImport } from './routes/risk'
import { Route as RiskDisclosureRouteImport } from './routes/risk-disclosure'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AssetSymbolRouteImport } from './routes/asset.$symbol'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as EmbedMomentumRouteImport } from './routes/embed.momentum'
import { Route as LpVariantRouteImport } from './routes/lp.$variant'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicMomentumRouteImport } from './routes/api/public/momentum'
import { Route as ApiPublicWaitlistRouteImport } from './routes/api/public/waitlist'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicWaitlistFollowupRouteImport } from './routes/api/public/waitlist/followup'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsReportRoute = AdsReportRouteImport.update({
  id: '/ads-report',
  path: '/ads-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const GoLiveTestRoute = GoLiveTestRouteImport.update({
  id: '/go-live-test',
  path: '/go-live-test',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LpReportRoute = LpReportRouteImport.update({
  id: '/lp-report',
  path: '/lp-report',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const McpConsoleRoute = McpConsoleRouteImport.update({
  id: '/mcp-console',
  path: '/mcp-console',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperRoute = PaperRouteImport.update({
  id: '/paper',
  path: '/paper',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferRoute = ReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskRoute = RiskRouteImport.update({
  id: '/risk',
  path: '/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskDisclosureRoute = RiskDisclosureRouteImport.update({
  id: '/risk-disclosure',
  path: '/risk-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AssetSymbolRoute = AssetSymbolRouteImport.update({
  id: '/asset/$symbol',
  path: '/asset/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedMomentumRoute = EmbedMomentumRouteImport.update({
  id: '/embed/momentum',
  path: '/embed/momentum',
  getParentRoute: () => rootRouteImport,
} as any)
const LpVariantRoute = LpVariantRouteImport.update({
  id: '/lp/$variant',
  path: '/lp/$variant',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMomentumRoute = ApiPublicMomentumRouteImport.update({
  id: '/api/public/momentum',
  path: '/api/public/momentum',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWaitlistRoute = ApiPublicWaitlistRouteImport.update({
  id: '/api/public/waitlist',
  path: '/api/public/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWaitlistFollowupRoute =
  ApiPublicWaitlistFollowupRouteImport.update({
    id: '/followup',
    path: '/followup',
    getParentRoute: () => ApiPublicWaitlistRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ads-report': typeof AdsReportRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/backtest': typeof BacktestRoute
  '/community': typeof CommunityRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/doctor': typeof DoctorRoute
  '/go-live-test': typeof GoLiveTestRoute
  '/journal': typeof JournalRoute
  '/learn': typeof LearnRoute
  '/lp-report': typeof LpReportRoute
  '/mcp': typeof McpRoute
  '/mcp-console': typeof McpConsoleRoute
  '/paper': typeof PaperRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refer': typeof ReferRoute
  '/refund': typeof RefundRoute
  '/risk': typeof RiskRoute
  '/risk-disclosure': typeof RiskDisclosureRoute
  '/scanner': typeof ScannerRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/strategy': typeof StrategyRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/asset/$symbol': typeof AssetSymbolRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/embed/momentum': typeof EmbedMomentumRoute
  '/lp/$variant': typeof LpVariantRoute
  '/blog/': typeof BlogIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/momentum': typeof ApiPublicMomentumRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRouteWithChildren
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/waitlist/followup': typeof ApiPublicWaitlistFollowupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ads-report': typeof AdsReportRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/backtest': typeof BacktestRoute
  '/community': typeof CommunityRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/doctor': typeof DoctorRoute
  '/go-live-test': typeof GoLiveTestRoute
  '/journal': typeof JournalRoute
  '/learn': typeof LearnRoute
  '/lp-report': typeof LpReportRoute
  '/mcp': typeof McpRoute
  '/mcp-console': typeof McpConsoleRoute
  '/paper': typeof PaperRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refer': typeof ReferRoute
  '/refund': typeof RefundRoute
  '/risk': typeof RiskRoute
  '/risk-disclosure': typeof RiskDisclosureRoute
  '/scanner': typeof ScannerRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/strategy': typeof StrategyRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/asset/$symbol': typeof AssetSymbolRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/embed/momentum': typeof EmbedMomentumRoute
  '/lp/$variant': typeof LpVariantRoute
  '/blog': typeof BlogIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/momentum': typeof ApiPublicMomentumRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRouteWithChildren
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/waitlist/followup': typeof ApiPublicWaitlistFollowupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ads-report': typeof AdsReportRoute
  '/alerts': typeof AlertsRoute
  '/auth': typeof AuthRoute
  '/backtest': typeof BacktestRoute
  '/community': typeof CommunityRoute
  '/copilot': typeof CopilotRoute
  '/dashboard': typeof DashboardRoute
  '/developers': typeof DevelopersRoute
  '/doctor': typeof DoctorRoute
  '/go-live-test': typeof GoLiveTestRoute
  '/journal': typeof JournalRoute
  '/learn': typeof LearnRoute
  '/lp-report': typeof LpReportRoute
  '/mcp': typeof McpRoute
  '/mcp-console': typeof McpConsoleRoute
  '/paper': typeof PaperRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refer': typeof ReferRoute
  '/refund': typeof RefundRoute
  '/risk': typeof RiskRoute
  '/risk-disclosure': typeof RiskDisclosureRoute
  '/scanner': typeof ScannerRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/strategy': typeof StrategyRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/asset/$symbol': typeof AssetSymbolRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/embed/momentum': typeof EmbedMomentumRoute
  '/lp/$variant': typeof LpVariantRoute
  '/blog/': typeof BlogIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/momentum': typeof ApiPublicMomentumRoute
  '/api/public/waitlist': typeof ApiPublicWaitlistRouteWithChildren
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/waitlist/followup': typeof ApiPublicWaitlistFollowupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ads-report'
    | '/alerts'
    | '/auth'
    | '/backtest'
    | '/community'
    | '/copilot'
    | '/dashboard'
    | '/developers'
    | '/doctor'
    | '/go-live-test'
    | '/journal'
    | '/learn'
    | '/lp-report'
    | '/mcp'
    | '/mcp-console'
    | '/paper'
    | '/pricing'
    | '/privacy'
    | '/refer'
    | '/refund'
    | '/risk'
    | '/risk-disclosure'
    | '/scanner'
    | '/security'
    | '/settings'
    | '/strategy'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/asset/$symbol'
    | '/blog/$slug'
    | '/embed/momentum'
    | '/lp/$variant'
    | '/blog/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/momentum'
    | '/api/public/waitlist'
    | '/api/public/payments/webhook'
    | '/api/public/waitlist/followup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ads-report'
    | '/alerts'
    | '/auth'
    | '/backtest'
    | '/community'
    | '/copilot'
    | '/dashboard'
    | '/developers'
    | '/doctor'
    | '/go-live-test'
    | '/journal'
    | '/learn'
    | '/lp-report'
    | '/mcp'
    | '/mcp-console'
    | '/paper'
    | '/pricing'
    | '/privacy'
    | '/refer'
    | '/refund'
    | '/risk'
    | '/risk-disclosure'
    | '/scanner'
    | '/security'
    | '/settings'
    | '/strategy'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/asset/$symbol'
    | '/blog/$slug'
    | '/embed/momentum'
    | '/lp/$variant'
    | '/blog'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/momentum'
    | '/api/public/waitlist'
    | '/api/public/payments/webhook'
    | '/api/public/waitlist/followup'
  id:
    | '__root__'
    | '/'
    | '/ads-report'
    | '/alerts'
    | '/auth'
    | '/backtest'
    | '/community'
    | '/copilot'
    | '/dashboard'
    | '/developers'
    | '/doctor'
    | '/go-live-test'
    | '/journal'
    | '/learn'
    | '/lp-report'
    | '/mcp'
    | '/mcp-console'
    | '/paper'
    | '/pricing'
    | '/privacy'
    | '/refer'
    | '/refund'
    | '/risk'
    | '/risk-disclosure'
    | '/scanner'
    | '/security'
    | '/settings'
    | '/strategy'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/asset/$symbol'
    | '/blog/$slug'
    | '/embed/momentum'
    | '/lp/$variant'
    | '/blog/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/momentum'
    | '/api/public/waitlist'
    | '/api/public/payments/webhook'
    | '/api/public/waitlist/followup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdsReportRoute: typeof AdsReportRoute
  AlertsRoute: typeof AlertsRoute
  AuthRoute: typeof AuthRoute
  BacktestRoute: typeof BacktestRoute
  CommunityRoute: typeof CommunityRoute
  CopilotRoute: typeof CopilotRoute
  DashboardRoute: typeof DashboardRoute
  DevelopersRoute: typeof DevelopersRoute
  DoctorRoute: typeof DoctorRoute
  GoLiveTestRoute: typeof GoLiveTestRoute
  JournalRoute: typeof JournalRoute
  LearnRoute: typeof LearnRoute
  LpReportRoute: typeof LpReportRoute
  McpRoute: typeof McpRoute
  McpConsoleRoute: typeof McpConsoleRoute
  PaperRoute: typeof PaperRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ReferRoute: typeof ReferRoute
  RefundRoute: typeof RefundRoute
  RiskRoute: typeof RiskRoute
  RiskDisclosureRoute: typeof RiskDisclosureRoute
  ScannerRoute: typeof ScannerRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  StrategyRoute: typeof StrategyRoute
  TermsRoute: typeof TermsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AssetSymbolRoute: typeof AssetSymbolRoute
  BlogSlugRoute: typeof BlogSlugRoute
  EmbedMomentumRoute: typeof EmbedMomentumRoute
  LpVariantRoute: typeof LpVariantRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicMomentumRoute: typeof ApiPublicMomentumRoute
  ApiPublicWaitlistRoute: typeof ApiPublicWaitlistRouteWithChildren
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads-report': {
      id: '/ads-report'
      path: '/ads-report'
      fullPath: '/ads-report'
      preLoaderRoute: typeof AdsReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go-live-test': {
      id: '/go-live-test'
      path: '/go-live-test'
      fullPath: '/go-live-test'
      preLoaderRoute: typeof GoLiveTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp-report': {
      id: '/lp-report'
      path: '/lp-report'
      fullPath: '/lp-report'
      preLoaderRoute: typeof LpReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp-console': {
      id: '/mcp-console'
      path: '/mcp-console'
      fullPath: '/mcp-console'
      preLoaderRoute: typeof McpConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper': {
      id: '/paper'
      path: '/paper'
      fullPath: '/paper'
      preLoaderRoute: typeof PaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refer': {
      id: '/refer'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof ReferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk': {
      id: '/risk'
      path: '/risk'
      fullPath: '/risk'
      preLoaderRoute: typeof RiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-disclosure': {
      id: '/risk-disclosure'
      path: '/risk-disclosure'
      fullPath: '/risk-disclosure'
      preLoaderRoute: typeof RiskDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset/$symbol': {
      id: '/asset/$symbol'
      path: '/asset/$symbol'
      fullPath: '/asset/$symbol'
      preLoaderRoute: typeof AssetSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/momentum': {
      id: '/embed/momentum'
      path: '/embed/momentum'
      fullPath: '/embed/momentum'
      preLoaderRoute: typeof EmbedMomentumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lp/$variant': {
      id: '/lp/$variant'
      path: '/lp/$variant'
      fullPath: '/lp/$variant'
      preLoaderRoute: typeof LpVariantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/momentum': {
      id: '/api/public/momentum'
      path: '/api/public/momentum'
      fullPath: '/api/public/momentum'
      preLoaderRoute: typeof ApiPublicMomentumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/waitlist': {
      id: '/api/public/waitlist'
      path: '/api/public/waitlist'
      fullPath: '/api/public/waitlist'
      preLoaderRoute: typeof ApiPublicWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/waitlist/followup': {
      id: '/api/public/waitlist/followup'
      path: '/followup'
      fullPath: '/api/public/waitlist/followup'
      preLoaderRoute: typeof ApiPublicWaitlistFollowupRouteImport
      parentRoute: typeof ApiPublicWaitlistRoute
    }
  }
}

interface ApiPublicWaitlistRouteChildren {
  ApiPublicWaitlistFollowupRoute: typeof ApiPublicWaitlistFollowupRoute
}

const ApiPublicWaitlistRouteChildren: ApiPublicWaitlistRouteChildren = {
  ApiPublicWaitlistFollowupRoute: ApiPublicWaitlistFollowupRoute,
}

const ApiPublicWaitlistRouteWithChildren =
  ApiPublicWaitlistRoute._addFileChildren(ApiPublicWaitlistRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdsReportRoute: AdsReportRoute,
  AlertsRoute: AlertsRoute,
  AuthRoute: AuthRoute,
  BacktestRoute: BacktestRoute,
  CommunityRoute: CommunityRoute,
  CopilotRoute: CopilotRoute,
  DashboardRoute: DashboardRoute,
  DevelopersRoute: DevelopersRoute,
  DoctorRoute: DoctorRoute,
  GoLiveTestRoute: GoLiveTestRoute,
  JournalRoute: JournalRoute,
  LearnRoute: LearnRoute,
  LpReportRoute: LpReportRoute,
  McpRoute: McpRoute,
  McpConsoleRoute: McpConsoleRoute,
  PaperRoute: PaperRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ReferRoute: ReferRoute,
  RefundRoute: RefundRoute,
  RiskRoute: RiskRoute,
  RiskDisclosureRoute: RiskDisclosureRoute,
  ScannerRoute: ScannerRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  StrategyRoute: StrategyRoute,
  TermsRoute: TermsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AssetSymbolRoute: AssetSymbolRoute,
  BlogSlugRoute: BlogSlugRoute,
  EmbedMomentumRoute: EmbedMomentumRoute,
  LpVariantRoute: LpVariantRoute,
  BlogIndexRoute: BlogIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicMomentumRoute: ApiPublicMomentumRoute,
  ApiPublicWaitlistRoute: ApiPublicWaitlistRouteWithChildren,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
